/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a9be6e630b6f3932a4fb45422d9f3c41)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DEV_AUTH_BYPASS: string;
	ROOMS: DurableObjectNamespace<import("./src/worker").Room>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
