/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f0220ce5275281418c3406bd29c248bb)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DEV_AUTH_BYPASS: string;
	ROOMS: DurableObjectNamespace<import("./src/worker").Room>;
	AUTH: Fetcher /* poietic-auth */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Room";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
